### ISSUE TITLE
Empty first line 

### ISSUE THREAD

**Issue by leskovia** [christianezeani/dokuwiki-plugin-codify#1]
Hello.
I noticed that code started at next line after tag "codify" renders with first empty line. Most other plugins not counting  line breaks right after tag.

**Comment by christianezeani** [comment]
Hi @leskovia. I actually noticed it earlier and planned to work on it much later. Now that you have called my attention to it, I'll look into it right away.

Thannks.

**Comment by christianezeani** [comment]
Hi @leskovia. Issue has been fixed.

**Comment by leskovia** [comment]
Hi! Very big thanks!

> Hi @leskovia. Issue has been fixed.

**Comment by christianezeani** [comment]
You're welcome @leskovia
