### ISSUE TITLE
Dark themes

### ISSUE THREAD

**Issue by Gamahost** [christianezeani/dokuwiki-plugin-codify#2]
Can we have dark themes?
I am using a dark template in the site and so the white text conflicts with the white backgroud in the default prism template.

**Comment by christianezeani** [comment]
Hi @Rayaqu,

Thanks for reaching out. The dark theme is coming soon. Admins will be able to choose from available themes in the next release which will be published before the end of the month.

You can hit the **Watch** button on the repository to get updates.

Kindly hit the **Star** button on the repository if you like this plugin.

**Comment by Gamahost** [comment]
Ohh, I do like it indeed.
Thank you for adding the feature, I needed it so bad!

**Comment by christianezeani** [comment]
Hi @Rayaqu,

A new version of codify has been published. Kindly update the plugin to the latest version.

Visit https://www.dokuwiki.org/plugin:codify for more info on how to change codify theme.

Thanks.
